-- V1: criação inicial de schema e tabelas para e-commerce
-- Banco: PostgreSQL
-- Schema: ECOMMERCE

-- 1) Schema
CREATE SCHEMA IF NOT EXISTS ECOMMERCE;

-- 3) Tabelas de catálogo de produtos
CREATE TABLE IF NOT EXISTS ECOMMERCE.product (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sku             TEXT        NOT NULL UNIQUE,
  name            TEXT        NOT NULL,
  description     TEXT,
  price_cents     BIGINT      NOT NULL CHECK (price_cents >= 0),
  currency        TEXT        NOT NULL DEFAULT 'BRL',
  active          BOOLEAN     NOT NULL DEFAULT TRUE,
  created_at      timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at      timestamp
);

CREATE TABLE IF NOT EXISTS ECOMMERCE.category (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name            TEXT        NOT NULL,
  description     TEXT,
  created_at      timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS ECOMMERCE.product_category (
  product_id      BIGINT      NOT NULL REFERENCES ECOMMERCE.product(id) ON DELETE CASCADE,
  category_id     BIGINT      NOT NULL REFERENCES ECOMMERCE.category(id) ON DELETE CASCADE,
  PRIMARY KEY (product_id, category_id)
);

-- 4) Usuários
CREATE TABLE IF NOT EXISTS ECOMMERCE.users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email           TEXT        NOT NULL UNIQUE,
  password_hash   TEXT        NOT NULL,
  role            VARCHAR(20) NOT NULL CHECK (role IN ('ADMIN','CLIENTE')),
  enabled         BOOLEAN     NOT NULL DEFAULT TRUE,
  created_at      timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 5) Carrinho e itens
CREATE TABLE IF NOT EXISTS ECOMMERCE.carts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id         BIGINT      NOT NULL UNIQUE  -- 1:1 usuário <-> carrinho
                REFERENCES ECOMMERCE.users(id) ON DELETE CASCADE,
  created_at      timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at      timestamp
);

CREATE TABLE IF NOT EXISTS ECOMMERCE.cart_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cart_id             BIGINT      NOT NULL REFERENCES ECOMMERCE.carts(id)   ON DELETE CASCADE,
  product_id          BIGINT      NOT NULL REFERENCES ECOMMERCE.product(id) ON DELETE RESTRICT,
  quantity            INTEGER     NOT NULL CHECK (quantity > 0),
  unit_price_snapshot BIGINT      NOT NULL CHECK (unit_price_snapshot >= 0),
  created_at          timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (cart_id, product_id) -- não repetir o mesmo produto no carrinho
);

-- 6) Pedido e itens do pedido
CREATE TABLE IF NOT EXISTS ECOMMERCE.orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id         BIGINT      NOT NULL REFERENCES ECOMMERCE.users(id) ON DELETE RESTRICT,
  status          VARCHAR(20) NOT NULL DEFAULT 'PENDING' CHECK (status IN('PENDING','PAID','SHIPPED','DELIVERED','CANCELLED')) ,
  total_cents     BIGINT      NOT NULL CHECK (total_cents >= 0),
  created_at      timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at      timestamp
);

CREATE TABLE IF NOT EXISTS ECOMMERCE.order_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id        BIGINT      NOT NULL REFERENCES ECOMMERCE.orders(id)  ON DELETE CASCADE,
  product_id      BIGINT      NOT NULL REFERENCES ECOMMERCE.product(id) ON DELETE RESTRICT,
  quantity        INTEGER     NOT NULL CHECK (quantity > 0),
  unit_price      BIGINT      NOT NULL CHECK (unit_price >= 0),
  created_at      timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_product_active         ON ECOMMERCE.product(active);
CREATE INDEX IF NOT EXISTS idx_product_sku            ON ECOMMERCE.product(sku);
CREATE INDEX IF NOT EXISTS idx_category_name          ON ECOMMERCE.category(name);
CREATE INDEX IF NOT EXISTS idx_users_email            ON ECOMMERCE.users(email);
CREATE INDEX IF NOT EXISTS idx_orders_user_id_status  ON ECOMMERCE.orders(user_id, status);
CREATE INDEX IF NOT EXISTS idx_order_items_order_id   ON ECOMMERCE.order_items(order_id);
CREATE INDEX IF NOT EXISTS idx_cart_items_cart_id     ON ECOMMERCE.cart_items(cart_id);

